spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.jt.entity
  config-location: classpath:mybatis-config.xml

---

spring:
  profiles: dev
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://10.0.3.213:3306/ai?serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

# open题库 数据源配置
ai:
  datasource:
    url: jdbc:mysql://10.0.3.213:3306/ai?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

# other 数据源配置

server:
  port: 8090

# Show sql log
logging:
  level:
     com.jt.mapper: debug

elasticSearch:
  host: 218.17.204.22
  port: 9200
  client:
    connectNum: 30
    connectPerRoute: 50