spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jt.entity
  config-location: classpath:mybatis-config.xml

---

spring:
  profiles: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.0.3.213:3306/ai?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8090

# Show sql log
logging:
  level:
     com:
       jt:
         mapper: debug